# Generated by Django 4.2.11 on 2024-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='background_color',
            field=models.CharField(default='red', max_length=7),
        ),
    ]
